hl.on("hyprland.start", function()
    local home = os.getenv("HOME")

    hl.exec_cmd("mako")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper --config " .. home .. "/.config/dotfiles-theme/hyprpaper.conf")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd(home .. "/.config/hypr/scripts/monitor-hotplug")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(home .. "/.config/hypr/scripts/auto-rotate")
    hl.exec_cmd(home .. "/.config/hypr/scripts/lightbar-off")
end)
