-- Generated by nwg-displays on 2026-08-14 at 12:42:10. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@180.0",
    position = "5120x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-9",
    mode = "2560x1440@59.95",
    position = "2560x0",
    scale = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "640x0",
    scale = 1
})
